version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/playground-logging/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 180
      runas: root
#    - location: scripts/health_check.sh
#      timeout: 180
#      runas: root
    - location: scripts/switch.sh
      timeout: 180
      runas: root





