server:
  port: 8081
  servlet:
    context-path: /
spring:
  profiles:
    active: prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(17+925ueQRcYNwllPFp/h0M3pJMT5wtgQxj34rk9KUo=)
    password: ENC(lf/LJBsc0lPkUX0Y9YbfQTjifUxi+NdNw3BOIbMmgtc=)
    properties:
      mail:
        smtp:
          port: 465
          auth: true
          starttls:
            required: true
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한

  redis:
    host: ENC(JRewTIiS/WWm2QxV1htiHs1G1ncWA4mP)
    port: 6379

# 제거
kakao:
  redirect: http://localhost:8080/auth/kakao/callback
  client:
    id: d5435649f10d74a354a9f02d17af6bdc
    secret: F2Yck6vsuPADPS6mxsEFaq2vlAPl6fjV
  url:
    login: https://kauth.kakao.com/oauth/authorize
    token: https://kauth.kakao.com/oauth/token
    profile: https://kapi.kakao.com/v2/user/me
    unlink: https://kapi.kakao.com/v1/user/unlink

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

token:
  secret: ENC(mhaQLulh9yzThpZv8PMZKtGeXkFgsqd9cW+1ZzftHAU=)
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주

cloud:
  aws:
    s3:
      bucket: ENC(BwxzMdaRgg/FmGsQOenTojVRUhBfjU1vmS3V4vEEV2k=)
    credentials:
      access-key: ENC(ZmyuYQmZw+8ptwqC+B6sLcaU+M3h0NMlwDmiR0tfTes=)
      secret-key: ENC(uhO98PMVUKNS9WB3s5XYarwG4DCQZEGlNkA6raXKZTFtjJZzMWlWnTumnPET2G+uICjQ4IpBGM0=)
    region:
      static: ap-northeast-2
    stack:
      auto: false

s3:
  users:
    path: /users
    default: default.png
  question:
    path: /questions
  answer:
    path: /answers
  community:
    path: /community

page:
  count: 15
