spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
#    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
#  datasource:
#    url: ENC(xQZj8IgmGHhxSsPsJg5HfbDlDESaMAGlJm9aM+rbqIOWSMAsGcMf6MTp2lk406yx2cMlyWlOKGGNQbqqVzuJbonRtNEJ9eahhq01cAqpoht2skNDYdh9Yi2ca+Io4bS6)
#    username: ENC(x9JT7KRP87tq9DxLC1Yf7g==)
#    password: ENC(97S/vqWIMLuAyJL4PutGI8GmTsInGsBl)
#    driver-class-name: com.mysql.jdbc.Driver
#      schema: classpath*:/schema.sql
#    data: classpath*:/data.sql
#    initialization-mode: always
  jpa:
    open-in-view: false
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            format_sql: true # sql 예쁘게 출력
            default_batch_fetch_size: 1000
    show-sql: true  # sql 출력
    generate-ddl: true
