spring:
  datasource:
    url: ENC(NFjs2fL+kacpK4NiY8OJo1VO9pEA+LjJYbPtdTIcrbKAjfTAMjmorNByeOkPYZB9ygAksX5Uuava17WneHsYncMyVNmKyZ2J96m3y3f5NvbkwxxbCcHztq1QwXa4qLPv)
    username: ENC(x9JT7KRP87tq9DxLC1Yf7g==)
    password: ENC(97S/vqWIMLuAyJL4PutGI8GmTsInGsBl)

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

